version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  web:
    image: wordpress:4.9.5-php5.6
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - db
    ports:
      - "80:80"
